rearrangement of notify_service_html (some guys got probs with escaping)

diff --git a/contrib/notify_service_html b/contrib/notify_service_html
--- a/contrib/notify_service_html
+++ b/contrib/notify_service_html
@@ -52,26 +52,9 @@ MAILBIN="$NAGIOSDIR/libexec/mailx"          # path to MIME capable mail client
 #
 #--- no adoptions necessary from here -----------------------------------------------
 #
-#--- 1. create HTML file
-cat <<HTMLEOF > "/tmp/mailx.$NAGIOS_HOSTNAME.$NAGIOS_SERVICEDESC.html"
-<html>
-<head>
-<title>Extended Information</title>
-<LINK REL='stylesheet' TYPE='text/css' HREF='$NAGIOS_URL/stylesheets/common.css'>
-<LINK REL='stylesheet' TYPE='text/css' HREF='$NAGIOS_URL/stylesheets/extinfo.css'>
-</head>
-<body CLASS='extinfo'>
-$NAGIOS_LONGSERVICEOUTPUT
-</body>
-</html>
-HTMLEOF
-MAIL_ATTACHMENT_HTML="/tmp/mailx.$NAGIOS_HOSTNAME.$NAGIOS_SERVICEDESC.html"
-if [ "x$NAGIOS_LONGSERVICEOUTPUT" != "x" ]; then
-        MAIL_ATTACHMENT_HTML_CALL="-a \"$MAIL_ATTACHMENT_HTML\""
-fi
-#
-#--- 2. create ASCII file
-cat <<EOF > "/tmp/mailx.$NAGIOS_HOSTNAME.$NAGIOS_SERVICEDESC.txt"
+#--- 1. create ASCII file
+MAIL_ATTACHMENT_TXT="/tmp/mailx.$NAGIOS_HOSTNAME.$NAGIOS_SERVICEDESC.txt"
+cat <<EOF > $MAIL_ATTACHMENT_TXT
 
 Nagios service notification
 $NAGIOS_NOTIFICATIONTYPE $NAGIOS_SERVICEDESC $NAGIOS_SERVICESTATE
@@ -109,11 +92,41 @@ Notification type      $NAGIOS_NOTIFICATIONTYPE
 EOF
 
 #
-#--- 3. put everything together into MIME mail and send it
-MAIL_ATTACHMENT_TXT="/tmp/mailx.$NAGIOS_HOSTNAME.$NAGIOS_SERVICEDESC.txt"
-echo "$NAGIOS_SERVICEOUTPUT" | $MAILBIN $MAIL_ATTACHMENT_HTML_CALL -a "$MAIL_ATTACHMENT_TXT" -s "$NAGIOS_NOTIFICATIONTYPE: Service $NAGIOS_HOSTNAME/$NAGIOS_SERVICEDESC is $NAGIOS_SERVICESTATE" $NAGIOS_CONTACTEMAIL; RC=$?
+#--- 2. LONGSERVICEOUTPUT available? put it into HTML MIME attachment and send it
+if [ "x$NAGIOS_LONGSERVICEOUTPUT" != "x" ]; then
+
+	#--- create HTML output
+	MAIL_ATTACHMENT_HTML="/tmp/mailx.$NAGIOS_HOSTNAME.$NAGIOS_SERVICEDESC.html"
+	cat <<HTMLEOF > $MAIL_ATTACHMENT_HTML
+<html>
+<head>
+<title>Extended Information</title>
+<LINK REL='stylesheet' TYPE='text/css' HREF='$NAGIOS_URL/stylesheets/common.css'>
+<LINK REL='stylesheet' TYPE='text/css' HREF='$NAGIOS_URL/stylesheets/extinfo.css'>
+</head>
+<body CLASS='extinfo'>
+$NAGIOS_LONGSERVICEOUTPUT
+</body>
+</html>
+HTMLEOF
+	echo "$NAGIOS_SERVICEOUTPUT" | \
+		$MAILBIN \
+		-a "$MAIL_ATTACHMENT_HTML" \
+		-a "$MAIL_ATTACHMENT_TXT"  \
+		-s "$NAGIOS_NOTIFICATIONTYPE: Service $NAGIOS_HOSTNAME/$NAGIOS_SERVICEDESC is $NAGIOS_SERVICESTATE" \
+		$NAGIOS_CONTACTEMAIL
 #
-#--- 4. cleanup if everything ok, error files will remain
+#--- 3. no LONGSERVICEOUTPUT available? just send normal ASCII mail
+else
+	echo "$NAGIOS_SERVICEOUTPUT" | \
+		$MAILBIN \
+		-a "$MAIL_ATTACHMENT_TXT" \
+		-s "$NAGIOS_NOTIFICATIONTYPE: Service $NAGIOS_HOSTNAME/$NAGIOS_SERVICEDESC is $NAGIOS_SERVICESTATE" \
+		$NAGIOS_CONTACTEMAIL
+fi
+RC=$?	# catch RC
+#
+#--- 4. cleanup if everything ok, in case of error files will remain for debugging
 if [ $RC -eq 0 ]; then
         rm -f "$MAIL_ATTACHMENT_TXT" "$MAIL_ATTACHMENT_HTML"
         rm -f /tmp/${MYSELF}-*$$
