configure now checks the existance of the 'nagios' user and bails out if it's not found, thanks to John S. Skogtvedt

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -623,13 +623,14 @@ PKG_ID
 SET_MAKE
 CHMOD
 CP
+ETHTOOL
+GUNZIP
+ID
 INSTALL_PROGRAM
 INSTALL_SCRIPT
 INSTALL_DATA
 INSTALL
 PERL
-ETHTOOL
-GUNZIP
 client_perl
 ac_configure_args
 action_mouseover
@@ -1866,6 +1867,126 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
+# Extract the first word of "ethtool", so it can be a program name with args.
+set dummy ethtool; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_ETHTOOL+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $ETHTOOL in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_ETHTOOL="$ETHTOOL" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_ETHTOOL="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+ETHTOOL=$ac_cv_path_ETHTOOL
+if test -n "$ETHTOOL"; then
+  { echo "$as_me:$LINENO: result: $ETHTOOL" >&5
+echo "${ECHO_T}$ETHTOOL" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+# Extract the first word of "gunzip", so it can be a program name with args.
+set dummy gunzip; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_GUNZIP+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $GUNZIP in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_GUNZIP="$GUNZIP" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_GUNZIP="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+GUNZIP=$ac_cv_path_GUNZIP
+if test -n "$GUNZIP"; then
+  { echo "$as_me:$LINENO: result: $GUNZIP" >&5
+echo "${ECHO_T}$GUNZIP" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+# Extract the first word of "id", so it can be a program name with args.
+set dummy id; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_ID+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $ID in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_ID="$ID" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_ID="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+ID=$ac_cv_path_ID
+if test -n "$ID"; then
+  { echo "$as_me:$LINENO: result: $ID" >&5
+echo "${ECHO_T}$ID" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
 ac_aux_dir=
 for ac_dir in "$srcdir" "$srcdir/.." "$srcdir/../.."; do
   if test -f "$ac_dir/install-sh"; then
@@ -2012,86 +2133,6 @@ PERL=$ac_cv_path_PERL
 if test -n "$PERL"; then
   { echo "$as_me:$LINENO: result: $PERL" >&5
 echo "${ECHO_T}$PERL" >&6; }
-else
-  { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-fi
-
-
-# Extract the first word of "ethtool", so it can be a program name with args.
-set dummy ethtool; ac_word=$2
-{ echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_path_ETHTOOL+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  case $ETHTOOL in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_ETHTOOL="$ETHTOOL" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_path_ETHTOOL="$as_dir/$ac_word$ac_exec_ext"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-IFS=$as_save_IFS
-
-  ;;
-esac
-fi
-ETHTOOL=$ac_cv_path_ETHTOOL
-if test -n "$ETHTOOL"; then
-  { echo "$as_me:$LINENO: result: $ETHTOOL" >&5
-echo "${ECHO_T}$ETHTOOL" >&6; }
-else
-  { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-fi
-
-
-# Extract the first word of "gunzip", so it can be a program name with args.
-set dummy gunzip; ac_word=$2
-{ echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_path_GUNZIP+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  case $GUNZIP in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_GUNZIP="$GUNZIP" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_path_GUNZIP="$as_dir/$ac_word$ac_exec_ext"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-IFS=$as_save_IFS
-
-  ;;
-esac
-fi
-GUNZIP=$ac_cv_path_GUNZIP
-if test -n "$GUNZIP"; then
-  { echo "$as_me:$LINENO: result: $GUNZIP" >&5
-echo "${ECHO_T}$GUNZIP" >&6; }
 else
   { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
@@ -2473,6 +2514,15 @@ else
 fi
 
 
+#--- check if user exists (thanks to John S. Skogtvedt)
+$ID $nagios_user >/dev/null
+if test $? -ne 0; then
+	{ { echo "$as_me:$LINENO: error: user '$nagios_user' does not exist." >&5
+echo "$as_me: error: user '$nagios_user' does not exist." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+#--- substitutions
 
 
 
@@ -3218,13 +3268,14 @@ PKG_ID!$PKG_ID$ac_delim
 SET_MAKE!$SET_MAKE$ac_delim
 CHMOD!$CHMOD$ac_delim
 CP!$CP$ac_delim
+ETHTOOL!$ETHTOOL$ac_delim
+GUNZIP!$GUNZIP$ac_delim
+ID!$ID$ac_delim
 INSTALL_PROGRAM!$INSTALL_PROGRAM$ac_delim
 INSTALL_SCRIPT!$INSTALL_SCRIPT$ac_delim
 INSTALL_DATA!$INSTALL_DATA$ac_delim
 INSTALL!$INSTALL$ac_delim
 PERL!$PERL$ac_delim
-ETHTOOL!$ETHTOOL$ac_delim
-GUNZIP!$GUNZIP$ac_delim
 client_perl!$client_perl$ac_delim
 ac_configure_args!$ac_configure_args$ac_delim
 action_mouseover!$action_mouseover$ac_delim
@@ -3268,7 +3319,6 @@ parent_timeout!$parent_timeout$ac_delim
 verbose!$verbose$ac_delim
 nagios_user!$nagios_user$ac_delim
 nagios_group!$nagios_group$ac_delim
-nagios_name!$nagios_name$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -3310,13 +3360,14 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+nagios_name!$nagios_name$ac_delim
 LIBEXECDIR!$LIBEXECDIR$ac_delim
 INSTALL_OPTS!$INSTALL_OPTS$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 4; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 5; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
